-- spec/density_spec.lua — Tests for density presets module
local density = require("sagefs.density")

describe("density presets", function()
  it("defaults to normal", function()
    local state = density.new()
    assert.are.equal("normal", state.preset)
  end)

  it("minimal preset shows signs only", function()
    local state = density.new()
    state = density.set(state, "minimal")
    assert.is_true(state.signs)
    assert.is_false(state.codelens)
    assert.is_false(state.inline_failures)
    assert.is_false(state.branch_eol)
  end)

  it("normal preset shows signs + codelens + inline failures", function()
    local state = density.new()
    state = density.set(state, "normal")
    assert.is_true(state.signs)
    assert.is_true(state.codelens)
    assert.is_true(state.inline_failures)
    assert.is_false(state.branch_eol)
  end)

  it("full preset shows everything", function()
    local state = density.new()
    state = density.set(state, "full")
    assert.is_true(state.signs)
    assert.is_true(state.codelens)
    assert.is_true(state.inline_failures)
    assert.is_true(state.branch_eol)
  end)

  it("cycle advances minimal -> normal -> full -> minimal", function()
    local state = density.new()
    state = density.set(state, "minimal")
    state = density.cycle(state)
    assert.are.equal("normal", state.preset)
    state = density.cycle(state)
    assert.are.equal("full", state.preset)
    state = density.cycle(state)
    assert.are.equal("minimal", state.preset)
  end)

  it("rejects unknown preset names", function()
    local state = density.new()
    local new_state = density.set(state, "bogus")
    -- Should stay unchanged
    assert.are.equal("normal", new_state.preset)
  end)

  it("should_render respects flags", function()
    local state = density.set(density.new(), "minimal")
    assert.is_true(density.should_render(state, "signs"))
    assert.is_false(density.should_render(state, "codelens"))
    assert.is_false(density.should_render(state, "inline_failures"))
    assert.is_false(density.should_render(state, "branch_eol"))
  end)
end)
