-- REPL freshness: whether the REPL and live tests run the same build as the
-- app. Shapes are the ones the dev daemon sent (spec/wire_fixtures.lua).
require("spec.helper")
local F = require("sagefs.repl_freshness")
local fx = require("spec.wire_fixtures")

local function sessions() return vim.json.decode(fx.read("api-sessions.json")).sessions end

local function behind(saves, declarations)
  return F.parse({ state = "BehindApp", savesSince = saves, declarations = declarations, message = "daemon words" })
end

describe("repl_freshness closed set", function()
  it("has the two states the daemon names", function()
    assert.are.same({ "InSync", "BehindApp" }, F.STATE.all)
  end)
end)

describe("repl_freshness.parse", function()
  it("reads the real BehindApp object from /api/sessions", function()
    local f = F.parse(sessions()[1].replFreshness)
    assert.are.equal("BehindApp", f.state)
    assert.are.equal(1, f.saves_since)
    assert.are.same({ "FalcoHello.Program.greet" }, f.declarations)
    assert.truthy(f.message:find("The REPL is BEHIND the app", 1, true))
    assert.truthy(f.message:find("hard_reset_fsi_session with rebuild=true", 1, true))
  end)

  it("reads the real InSync object", function()
    local f = F.parse(sessions()[2].replFreshness)
    assert.are.equal("InSync", f.state)
    assert.is_false(F.is_behind(f))
  end)

  it("returns nil when the daemon sent nothing, so an older daemon is never read as in sync", function()
    assert.is_nil(F.parse(nil))
    assert.is_nil(F.parse("InSync"))
  end)

  it("keeps a state outside the closed set, marked unknown", function()
    local f = F.parse({ state = "Sideways" })
    assert.are.equal("Sideways", f.state)
    assert.is_false(f.known)
    assert.is_false(F.is_behind(f))
  end)
end)

describe("repl_freshness.segment (statusline)", function()
  it("is empty when in sync or unknown", function()
    assert.are.equal("", F.segment(F.parse({ state = "InSync" })))
    assert.are.equal("", F.segment(nil))
  end)

  it("says BEHIND with the save count when behind", function()
    assert.are.equal("\u{26A0} REPL BEHIND app (1 save)", F.segment(behind(1, { "A.f" })))
    assert.are.equal("\u{26A0} REPL BEHIND app (3 saves)", F.segment(behind(3, { "A.f", "B.g" })))
  end)

  it("shows an unrecognized state instead of hiding it", function()
    assert.are.equal("REPL freshness: Sideways?", F.segment(F.parse({ state = "Sideways" })))
  end)
end)

describe("repl_freshness.eval_message (one line, with the remedy)", function()
  it("names the count, the declarations, the consequence, the remedy, and that the app stops", function()
    local msg = F.eval_message(behind(2, { "Handlers.describe", "Handlers.makeHeld" }))
    assert.is_nil(msg:find("\n", 1, true))
    assert.truthy(msg:find("The REPL is BEHIND the app", 1, true))
    assert.truthy(msg:find("2 saves", 1, true))
    assert.truthy(msg:find("Handlers.describe, Handlers.makeHeld", 1, true))
    assert.truthy(msg:find("OLD code", 1, true))
    assert.truthy(msg:find(":SageFsHardReset", 1, true))
    assert.truthy(msg:find("stops the running app", 1, true))
    assert.truthy(msg:find(":SageFsRunApp", 1, true))
  end)

  it("names the first three declarations and counts the rest", function()
    local msg = F.eval_message(behind(5, { "A.a", "A.b", "A.c", "A.d", "A.e" }))
    assert.truthy(msg:find("A.a, A.b, A.c, and 2 more", 1, true))
    assert.is_nil(msg:find("A.d,", 1, true))
  end)

  it("is nil when the REPL is level or the state is unknown", function()
    assert.is_nil(F.eval_message(F.parse({ state = "InSync" })))
    assert.is_nil(F.eval_message(nil))
  end)
end)

describe("repl_freshness.lines (panel)", function()
  it("gives the one-line message and the daemon's own words when behind", function()
    local lines = F.lines(behind(1, { "A.f" }))
    assert.is_true(#lines >= 2)
    assert.truthy(lines[1].text:find("REPL is BEHIND the app", 1, true))
    assert.are.equal("SageFsReplBehind", lines[1].hl)
  end)

  it("says in sync when in sync, and nothing when unknown", function()
    assert.are.equal("REPL in sync with the app", F.lines(F.parse({ state = "InSync" }))[1].text)
    assert.are.same({}, F.lines(nil))
  end)
end)

describe("repl_freshness.split_banner: the WARNING line the daemon puts after a tool's text result", function()
  it("separates the real /exec body from its banner", function()
    local body = vim.json.decode(fx.read("exec-behind-app.json"))
    local clean, banner = F.split_banner(body.result)
    assert.are.equal("Result: val it: int = 2", clean)
    assert.truthy(banner:find("^WARNING: The REPL is BEHIND the app"))
    assert.is_nil(clean:find("WARNING", 1, true))
  end)

  it("leaves a result with no banner alone", function()
    local clean, banner = F.split_banner("val x: int = 1")
    assert.are.equal("val x: int = 1", clean)
    assert.is_nil(banner)
  end)

  it("handles non-strings", function()
    local clean, banner = F.split_banner(nil)
    assert.is_nil(clean)
    assert.is_nil(banner)
  end)

  it("turns a banner into a BehindApp state whose message is the banner without the WARNING prefix", function()
    local body = vim.json.decode(fx.read("exec-behind-app.json"))
    local _, banner = F.split_banner(body.result)
    local f = F.from_banner(banner)
    assert.are.equal("BehindApp", f.state)
    assert.truthy(f.message:find("^The REPL is BEHIND the app"))
    assert.is_nil(f.saves_since)
  end)
end)

describe("repl_freshness.from_structured: the replFreshness field on send_fsharp_code and run_tests results", function()
  it("reads the field next to the result", function()
    local f = F.from_structured({ success = true, replFreshness = { state = "BehindApp", savesSince = 2, declarations = { "A.f" }, message = "m" } })
    assert.are.equal(2, f.saves_since)
  end)

  it("is nil when the result has no field", function()
    assert.is_nil(F.from_structured({ success = true }))
    assert.is_nil(F.from_structured(nil))
  end)
end)

describe("repl_freshness.gate: the eval message is impossible to miss but not noisy", function()
  it("announces the first time, stays quiet for the same state, repeats after a minute, and speaks up at once when it changes", function()
    local gate = F.gate_new()
    local f1 = behind(1, { "A.f" })
    local say
    say, gate = F.gate_should_announce(gate, f1, 0)
    assert.is_true(say)
    say, gate = F.gate_should_announce(gate, f1, 5000)
    assert.is_false(say)
    say, gate = F.gate_should_announce(gate, f1, 59999)
    assert.is_false(say)
    say, gate = F.gate_should_announce(gate, f1, 60000)
    assert.is_true(say)
    local f2 = behind(2, { "A.f", "B.g" })
    say, gate = F.gate_should_announce(gate, f2, 60500)
    assert.is_true(say)
  end)

  it("never announces when level, and forgets so the next time behind announces at once", function()
    local gate = F.gate_new()
    local say
    say, gate = F.gate_should_announce(gate, behind(1, { "A.f" }), 0)
    assert.is_true(say)
    say, gate = F.gate_should_announce(gate, F.parse({ state = "InSync" }), 10)
    assert.is_false(say)
    say, gate = F.gate_should_announce(gate, behind(1, { "A.f" }), 20)
    assert.is_true(say)
    say, gate = F.gate_should_announce(gate, nil, 30)
    assert.is_false(say)
  end)
end)
