-- spec/util_spec.lua — Tests for shared json_decode utility
local helper = require("spec.helper")
local util = require("sagefs.util")

describe("sagefs.util", function()
  describe("json_decode", function()
    it("decodes valid JSON object", function()
      local ok, data = util.json_decode('{"name":"test","value":42}')
      assert.is_true(ok)
      assert.equals("test", data.name)
      assert.equals(42, data.value)
    end)

    it("decodes valid JSON array", function()
      local ok, data = util.json_decode('[1,2,3]')
      assert.is_true(ok)
      assert.equals(3, #data)
    end)

    it("returns false for invalid JSON", function()
      local ok, _ = util.json_decode("{bad json")
      assert.is_false(ok)
    end)

    it("returns false for nil input", function()
      local ok, _ = util.json_decode(nil)
      assert.is_false(ok)
    end)

    it("returns false for empty string", function()
      local ok, _ = util.json_decode("")
      assert.is_false(ok)
    end)

    it("handles nested objects", function()
      local ok, data = util.json_decode('{"a":{"b":{"c":1}}}')
      assert.is_true(ok)
      assert.equals(1, data.a.b.c)
    end)

    it("handles boolean values", function()
      local ok, data = util.json_decode('{"enabled":true,"disabled":false}')
      assert.is_true(ok)
      assert.is_true(data.enabled)
      assert.is_false(data.disabled)
    end)

    it("handles null values", function()
      local ok, data = util.json_decode('{"key":null}')
      assert.is_true(ok)
      assert.is_table(data)
    end)
  end)
end)
